import Head from "next/head";
import { useQuery, gql } from "@apollo/client";

const GET_RECIPES = gql`
  query Recipes {
    recipes {
      title
      description
    }
  }
`;

export default function Home() {
  const { loading, error, data } = useQuery(GET_RECIPES);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {data.recipes.map(({ title, description }, i) => (
          <li key={i}>
            {title} ({description})
          </li>
        ))}
      </ul>
    </>
  );
}
